### ISSUE TITLE
Object movement sounds get triggered when another object is moving

### ISSUE THREAD

**Issue by ClementSparrow** [ClementSparrow/Pattern-Script#22]
See [this example](https://github.com/ClementSparrow/Pattern-Script/files/7014668/broken_sound.txt): pressing left triggers the sound of the crate moving even if the crate does not move in the end.

The reason is the test in `repositionEntitiesOnLayer` is bugged and will trigger a motion sound if the moving object is present in the cell and has a motion set, but it does not check that the object is actually in the layer considered. So, sounds will be triggered for all objects in that cell with motion when at least one object is successfully moving without colliding (even if it has no motion sound).

@increpare, the bug also exists in PuzzleScript, but you might want to wait that I have fixed it, since I'm working on it.

**Comment by increpare** [comment]
Good catch!

**Comment by ClementSparrow** [comment]
Actually, there is still a bug: in [this example](https://github.com/ClementSparrow/Pattern-Script/files/7020742/broken_sound2.txt), sound should be triggered when a target or a red crate moves, but it is triggered also when the cell contains a target and a moving object that is not a red crate but belongs to the same collision layer than red crates (player, orange crate...)
