### ISSUE TITLE
Large sprites not rendered properly

### ISSUE THREAD

**Issue by janIpen** [ClementSparrow/Pattern-Script#44]
When I made a sprite more than 1 tile thick, it didn't render completely.
Also, in the level editor, the top-left tile was shown instead of the bottom-left or the whole thing.

**Comment by ClementSparrow** [comment]
Yes, the sprites are still rendered from top to bottom, then left to right, as in vanilla PuzzleScript. As a consequence, if a sprite extends on the tiles on its right or below, it can be overdrawn by other sprites drawn later. I have simple plans to give more flexibility to this system but they are waiting for the completion of the new big feature (tm) that I'm currently working on.

If that's something that you really need quickly, I can prioritize that if you want.

I'm not sure about the problem with the editor, is it that in the legend palette, the sprites overwrite others? or that sprites extend over the border of the level? That's two known issues that I also need to fix.

**Comment by ClementSparrow** [comment]
See also the discussion in #8.
