### ISSUE TITLE
Console log errors when run on local server

### ISSUE THREAD

**Issue by david-pfx** [ClementSparrow/Pattern-Script#62]
Using runserver.bat to start a local server. Console log shows multiple errors;
```
The script from “http://localhost:8000/src/Documentation/js/jquery.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type.
[src](http://localhost:8000/src/)
The script from “http://localhost:8000/src/Documentation/js/bootstrap.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type.
[src](http://localhost:8000/src/)
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [src](http://localhost:8000/src/)
Loading failed for the <script> with source “https://s0.wp.com/wp-content/js/bilmur.min.js?m=202315”. [src:1327:1](http://localhost:8000/src/)
Uncaught TypeError: window.Tumblr is undefined

```...etc

It's not stable, and varies from one browser to another. I think the main problem is with Tumblr, but it's really hard to say.
Bottom line is: currently unable to run local server for dev purposes.

**Comment by david-pfx** [comment]
Gotcha! The problem is in the gallery, not in the editor. I can work around that.

But I can't fix it. Maybe it can't be fixed as long as P:S uses Tumblr.

**Comment by ClementSparrow** [comment]
`runserver.bat` is deprecated in Pattern:Script and should not be used and so is the gallery. I seriously considered removing these deprecated files from the project but decided to let them in case someone wants to make a fork that uses them. Now I'm not sure it was the wisest choice. I will update the project's page to add information about that.

**Comment by david-pfx** [comment]
I tried it with a different local server -- similar problem. It's not `runserver.bat` causing the problem. It's using Tumblr that's doing it.

I think you need a gallery, if you want people to use it your product. I've run a software business for years and I'm very conscious of who the customer is and why you need them. Again, it's your call. I can only tell you how it looks to me.

**Comment by ClementSparrow** [comment]
I totally agree a gallery would be great, I just think it should not be in the same repository than Pattern:Script. I want other people to be able to fork Pattern:Script and keep their forks updated without receiving a notification every time I add a game to the gallery.

**Comment by ClementSparrow** [comment]
Also, I realize I failed to provide the real useful information for this issue: Pattern:Script is not supposed to be run by users on a local server, it's only for contributors of the project. So I will not make any effort to fix issues that only appear in this context, unless they really break P:S development's workflow. Which is not the case, here, I think. But thanks for writing the report anyway, the effort is appreciated!

**Comment by david-pfx** [comment]
Agreed. And a dependency on Tumblr just compounds the problem.
