### ISSUE TITLE
Missing prelude items

### ISSUE THREAD

**Issue by david-pfx** [ClementSparrow/Pattern-Script#75]
Prelude items `game_uri` and `auto_level_titles` do not seem to be documented anywhere.

They are used in the Tapaban game.

For consistency, it would be better to call it `game_url` or `game_link`.

**Comment by ClementSparrow** [comment]
`auto_level_titles` is documented in the online doc: https://clementsparrow.github.io/Pattern-Script/src/Documentation/prelude.html

`game_uri` is not in the doc because it is still an experimental feature. And it's not a link or URL, it's really an URI, a Unique game Identifier.
