### ISSUE TITLE
An invalid mapping causes an exception

### ISSUE THREAD

**Issue by david-pfx** [ClementSparrow/Pattern-Script#76]
Repro case based on CastleMouse:
```
AnimalType => Frightening
Elephant Dog Cat Mouse -> Mouse Elephant Dog Catxxx
```
Triggers the error:
```
Uncaught TypeError: this.tag_mappings[identifier_index] is undefined
    replace_parameters https://clementsparrow.github.io/Pattern-Script/src/js/compiler/identifiers.js:675
    applyRuleParametersMappings https://clementsparrow.github.io/Pattern-Script/src/js/compiler/rule_expansion.js:62
    expandRule https://clementsparrow.github.io/Pattern-Script/src/js/compiler/rule_expansion.js:41
    rulesToArray https://clementsparrow.github.io/Pattern-Script/src/js/compiler/rule_expansion.js:90
    compileTextCode https://clementsparrow.github.io/Pattern-Script/src/js/compiler.js:992
    compile https://clementsparrow.github.io/Pattern-Script/src/js/compiler.js:1055
    runClick https://clementsparrow.github.io/Pattern-Script/src/js/toolbar.js:19
    onKeyDown https://clementsparrow.github.io/Pattern-Script/src/js/inputoutput.js:133
```

**Comment by ClementSparrow** [comment]
Thanks for sharing, but unfortunately I cannot reproduce the bug. Could you share the whole game source or a minimal working example, and provide information about your system and browser?

**Comment by david-pfx** [comment]
1. https://clementsparrow.github.io/Pattern-Script/src/editor.html
2. Copy and paste in `castlemouse.txt`, from GitHub
3. Compile and run. OK
4. Edit mapping line to read `Elephant Dog Cat Mouse -> Mouse Elephant Dog Catxxx`
5. Compile and crash.

[BTW the Rules display still shows the previous compile. Shouldn't it be cleared or something?]

**Comment by ClementSparrow** [comment]
Thanks! I was able to reproduce the bug. So, a first problem is it should raise a parsing error when this happens. This is easy to fix, and it would clear the console (the concern expressed at the end of your message).

Now, a second problem is dealing with the rules that use the invalid pattern. Doing it correctly would require huge changes. I'm thinking about a trick to make it easier (and not wrong, although not elegant), we'll see if that works.

edit: it seems to work, but it triggers a cascade of errors where the mapping is used in rules.

**Comment by david-pfx** [comment]
I would encourage you to write a few more notes on tags and mappings. I ran across this bug experimenting, trying to figure out what works and what doesn't by tweaking existing games. The docs as they are leave a lot unsaid.😀
